# Generated by Django 5.1.4 on 2024-12-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='border_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('info', 'Info'), ('dnager', 'Danger'), ('warning', 'Warning'), ('dark', 'Dark')], default='secondary', max_length=12, null=True),
        ),
    ]
