# Generated by Django 5.1.4 on 2024-12-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_border_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='border_color',
        ),
        migrations.AddField(
            model_name='account',
            name='color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('info', 'Info'), ('danger', 'Danger'), ('warning', 'Warning'), ('dark', 'Dark')], default='secondary', max_length=12, null=True),
        ),
    ]
